import type { FlagTemplate } from "../../_components/types";

export const HARDCODED_TEMPLATES: FlagTemplate[] = [
	{
		id: "gradual-rollout",
		name: "Gradual Rollout",
		description: "Start at 10% and ramp up over time.",
		category: "rollout",
		icon: "rocket",
		type: "rollout",
		defaultValue: false,
		rolloutPercentage: 10,
		isBuiltIn: true,
	},
	{
		id: "ab-test",
		name: "A/B Test (50/50)",
		description: "Even 50/50 split between control and variant.",
		category: "experiment",
		icon: "test",
		type: "rollout",
		defaultValue: false,
		rolloutPercentage: 50,
		isBuiltIn: true,
	},
	{
		id: "beta-program",
		name: "Beta Program",
		description: "Early access for users tagged as beta testers.",
		category: "targeting",
		icon: "users",
		type: "boolean",
		defaultValue: false,
		rules: [
			{
				type: "property",
				operator: "equals",
				field: "beta_tester",
				value: "true",
				enabled: true,
				batch: false,
			},
		],
		isBuiltIn: true,
	},
	{
		id: "internal-only",
		name: "Internal Team Only",
		description: "Enable only for your team's email domain.",
		category: "targeting",
		icon: "users",
		type: "boolean",
		defaultValue: false,
		rules: [
			{
				type: "email",
				operator: "ends_with",
				value: "@yourcompany.com",
				enabled: true,
				batch: false,
			},
		],
		isBuiltIn: true,
	},
	{
		id: "kill-switch",
		name: "Emergency Kill Switch",
		description: "Flip a feature off instantly during incidents.",
		category: "killswitch",
		icon: "warning",
		type: "boolean",
		defaultValue: true,
		rolloutPercentage: 100,
		isBuiltIn: true,
	},
	{
		id: "premium-only",
		name: "Premium Users Only",
		description: "Limit a feature to users on the premium plan.",
		category: "targeting",
		icon: "users",
		type: "boolean",
		defaultValue: false,
		rules: [
			{
				type: "property",
				operator: "equals",
				field: "subscription_tier",
				value: "premium",
				enabled: true,
				batch: false,
			},
		],
		isBuiltIn: true,
	},
	{
		id: "canary-release",
		name: "Canary Release (5%)",
		description: "Test with 5% of users before going wider.",
		category: "rollout",
		icon: "rocket",
		type: "rollout",
		defaultValue: false,
		rolloutPercentage: 5,
		isBuiltIn: true,
	},
	{
		id: "abc-test",
		name: "A/B/C Test (33%)",
		description: "Enable for one third of users.",
		category: "experiment",
		icon: "test",
		type: "rollout",
		defaultValue: false,
		rolloutPercentage: 33,
		isBuiltIn: true,
	},
	{
		id: "vip-users",
		name: "VIP Users",
		description: "Target users tagged as VIP accounts.",
		category: "targeting",
		icon: "users",
		type: "boolean",
		defaultValue: false,
		rules: [
			{
				type: "property",
				operator: "equals",
				field: "account_type",
				value: "vip",
				enabled: true,
				batch: false,
			},
		],
		isBuiltIn: true,
	},
	{
		id: "regional-release",
		name: "Regional Release",
		description: "Enable in specific countries (default: US, CA, GB).",
		category: "targeting",
		icon: "users",
		type: "boolean",
		defaultValue: false,
		rules: [
			{
				type: "property",
				operator: "in",
				field: "country",
				values: ["US", "CA", "GB"],
				enabled: true,
				batch: false,
			},
		],
		isBuiltIn: true,
	},
	{
		id: "multivariant-ab-test",
		name: "A/B Test Variants",
		description: "Two variants split 50/50 with custom return values.",
		category: "experiment",
		icon: "test",
		type: "multivariant",
		defaultValue: false,
		variants: [
			{
				key: "control",
				value: "control",
				weight: 50,
				description: "Control group - no changes",
				type: "string",
			},
			{
				key: "variant-a",
				value: "variant-a",
				weight: 50,
				description: "Variant A - new experience",
				type: "string",
			},
		],
		isBuiltIn: true,
	},
	{
		id: "pricing-tiers",
		name: "Pricing Tier Test",
		description: "Test three numeric price points ($9, $19, $29).",
		category: "experiment",
		icon: "test",
		type: "multivariant",
		defaultValue: false,
		variants: [
			{
				key: "low",
				value: 9,
				weight: 33,
				description: "Low price point",
				type: "number",
			},
			{
				key: "medium",
				value: 19,
				weight: 34,
				description: "Medium price point",
				type: "number",
			},
			{
				key: "high",
				value: 29,
				weight: 33,
				description: "High price point",
				type: "number",
			},
		],
		isBuiltIn: true,
	},
	{
		id: "theme-test",
		name: "UI Theme Test",
		description: "Test default, dark, and high-contrast themes.",
		category: "experiment",
		icon: "test",
		type: "multivariant",
		defaultValue: false,
		variants: [
			{
				key: "default",
				value: "default",
				weight: 50,
				description: "Default theme",
				type: "string",
			},
			{
				key: "dark",
				value: "dark",
				weight: 25,
				description: "Dark theme",
				type: "string",
			},
			{
				key: "contrast",
				value: "high-contrast",
				weight: 25,
				description: "High contrast theme",
				type: "string",
			},
		],
		isBuiltIn: true,
	},
];
