export const UA_PATTERNS: Record<string, string[]> = {
	ACADEMIC: [
		"a patent crawler",
		"academicbotrtu",
		"blackboard",
		"bnf.fr_bot",
		"bubing",
		"cispa webcrawler",
		"findlink",
		"https://www.loc.gov/programs/web-archiving/for-site-owners/",
		"macocu",
		"netarkivindsamling",
		"sonic",
		"turnitin",
		"ut-dorkbot",
	],
	ACCESSIBILITY: [
		"accessiblewebbot",
		"freshping",
		"google-read-aloud",
		"noibu",
		"pro-sitemaps/",
		"readable/",
		"silktide",
		"wovncrawler",
	],
	ADVERTISING: [
		"adidxbot",
		"adsbot-google",
		"adsbot-google-mobile",
		"amazonadbot",
		"bigupdatabot",
		"brightedge crawler",
		"channable/importer",
		"clickagy intelligence bot v2",
		"compatible; proximic",
		"contextualbot",
		"contxbot",
		"criteobot/",
		"google-ads-conversions",
		"google-display-ads-bot",
		"google-firebase",
		"grapeshotcrawler",
		"groovinaadsbot",
		"ias_crawler",
		"interactiveadvertisingbureau",
		"klaviyo/1.0",
		"leikibot",
		"mediapartners-google",
		"mediavinemetadataparser/",
		"meta-externalads/1.1",
		"mgidbot",
		"missinglettrbot",
		"moatbot",
		"msnbot",
		"noorobot",
		"nostocrawlerbot",
		"outbrain",
		"page-preview-tool",
		"productsup.io/crawler",
		"quantcastbot",
		"reelevant/",
		"sfdc-callout",
		"slickbot",
		"smartologybot",
		"taboolabot",
		"ttd-content",
		"y!j-asr",
		"y!j-brj/yats crawler",
		"y!j-bru/vsidx",
		"y!j-brw",
		"y!j-bry/yatsh crawler",
		"y!j-brz/yatsha crawler",
		"y!j-b|yj-sad",
		"y!j-mmp/dscv",
		"y!j-wsc",
		"yahoo ad monitoring",
		"yextbot",
		"yj-sad",
	],
	AGGREGATOR: [
		"bestchange",
		"boardgameprices bot",
		"capitalonebot",
		"channel3bot",
		"emoneybot/",
		"epivozcrawler/",
		"fedreporterdatabot",
		"indeedjobbot",
		"magnet.me-web/",
		"mediamonitoringbot/",
		"mediatoolkitbot",
		"mirrorweb",
		"motominerbot",
		"pinterest.com/",
		"statabot",
		"statsdronebot",
		"upday/",
		"videootvbot",
		"webspidermount",
	],
	AI_ASSISTANT: [
		"4f.at/crawler",
		"amazonbuyforme",
		"apifywebsitecontentcrawler",
		"chatgpt-user",
		"cohere-ai",
		"gemini-deep-research",
		"novaact",
		"perplexity-user",
		"cledarabot",
		"devin",
		"duckassistbot",
		"easyscan",
		"flockwp",
		"google-agent",
		"haiku-searchbot",
		"known agent",
		"meta-externalfetcher/",
		"mistralai-user",
		"nava/",
		"scavobot",
		"slopsearch",
		"spyglassesbot",
		"twinagent",
		"zipchatbot",
	],
	AI_CRAWLER: [
		"adpresearchbot/",
		"ai2bot",
		"ai2bot-dolma",
		"aihitbot",
		"aisearchbot",
		"amazon-kendra-",
		"amazonbot",
		"anchor browser",
		"anthropic-ai",
		"atlassian-bot",
		"awario",
		"bigsur.ai",
		"bytespider",
		"ccbot",
		"chatglm-spider",
		"citibotsitecrawler",
		"claudebot",
		"claude-searchbot",
		"claude-web",
		"cloudflarebrowserrenderingcrawler/1.0",
		"cloudvertexbot",
		"cohere-ai",
		"cohere-training-data-crawler",
		"cotoyogi/",
		"coveobot",
		"crunchbot",
		"dataforseobot",
		"deepseekbot",
		"diffbot",
		"factset_spyderbot",
		"facebookbot",
		"firecrawlagent",
		"friendlycrawler",
		"google-cloudvertexbot",
		"google-extended",
		"googleother",
		"gptbot",
		"huggingface-bot",
		"ias crawler",
		"iaskspider",
		"icc-crawler",
		"icc-crawler/",
		"imagesiftbot",
		"img2dataset",
		"linerbot",
		"magpie-crawler",
		"meta-externalagent",
		"meta-externalfetcher",
		"netestate ne crawler",
		"notebooklm",
		"novellum",
		"ntentbot",
		"kangaroo bot",
		"omgili",
		"omgilibot",
		"pangubot",
		"petalbot",
		"perplexitybot",
		"primalbot",
		"qualifiedbot",
		"replicate-bot",
		"runpod-bot",
		"safednsbot",
		"sbintuitionsbot",
		"searchatlas",
		"semanticscholarbot",
		"semrushbot-ocob",
		"semrushbot-swa/",
		"sentibot",
		"shapbot/",
		"storygizebot",
		"tiktokspider",
		"timpibot",
		"together-bot",
		"v0bot",
		"velenpublicwebcrawler",
		"w4mwnpbxf3mfabxokjrw",
		"wardbot",
		"webzio-extended",
		"xai-bot",
		"ygs-scraper-bot",
		"youbot",
	],
	AI_SEARCH: [
		"anomura",
		"applebot",
		"bravebot",
		"cloudflare-ai-search",
		"oai-searchbot",
	],
	ARCHIVER: [
		"archive-it",
		"archive.org_bot",
		"arquivo-web-crawler",
		"cloudflare-alwaysonline",
		"ezid",
		"heritrix",
		"nicecrawler",
	],
	FEED_FETCHER: [
		"artemis web reader/",
		"atom feed robot",
		"awariorssbot",
		"bazqux",
		"blogtrottr",
		"buttondown",
		"convermax/",
		"cozi-icalendar-feedreader",
		"feedbin",
		"feedbot",
		"feeder.co",
		"feedfetcher-google",
		"feedly",
		"feedly/1",
		"feedspot",
		"feedwind/",
		"flipboardrss",
		"follow.it",
		"freshrss",
		"g2reader-bot",
		"google.com/feedfetcher",
		"googleproducer",
		"hatena",
		"hubspot-feedfetcher",
		"ifttt",
		"innguma",
		"inoreader",
		"inoreader.com",
		"monitorss/",
		"muckrack.com",
		"naver blog rssbot",
		"newsblur",
		"nooshub",
		"openrss",
		"overcast/1.0 podcast sync",
		"pocket casts feed parser",
		"pocketparser",
		"protopage",
		"refindbot",
		"rss2tg bot",
		"rssapi/",
		"rssingbot",
		"scour.ing",
		"serendeputybot",
		"skroutzbot",
		"superfeedr",
		"tiny tiny rss",
	],
	MONITORING: [
		"a360-search",
		"accessstatus",
		"activecomply",
		"adagiobot",
		"alertsite",
		"amazon route 53 health check service",
		"appinsights",
		"audisto crawler",
		"better stack",
		"better uptime bot",
		"bigscootsmonitor",
		"blogvault/",
		"brandverity",
		"bugsnag",
		"catchpoint",
		"changedetection",
		"checkly",
		"cloudflarediagnostics",
		"cloudtrellis",
		"cludo.com",
		"contentking",
		"crazy egg",
		"curl/7.58.0-dev",
		"curly-",
		"datadog",
		"deadlinkchecker",
		"disqus",
		"dlc/",
		"dmbrowser",
		"elmahio-uptimebot",
		"erepublik.tools",
		"evouptimebot/",
		"fdl stats bot",
		"feedvalidator",
		"foregenix",
		"freewebmonitoring sitechecker",
		"freshpingbot",
		"fullstorybot",
		"ghost inspector",
		"google-certificates-bridge",
		"google-structured-data-testing",
		"grafana/synthetic-monitoring",
		"gtmetrix",
		"guestpostsbot/",
		"hetrixtools",
		"honeybadger uptime check",
		"hosttracker",
		"hotjar",
		"http://easyurl.net/monitoring",
		"http://www.binarycanary.com",
		"http://www.pingdom.com/",
		"hubspot",
		"iabot/",
		"isdownbot",
		"jetmon",
		"kargobot-artemis",
		"kinsta-bot",
		"linktiger",
		"logicmonitor sitemonitor/",
		"lumar",
		"macrobondbot",
		"mavifinds",
		"mbcrawler",
		"mediaboardbot",
		"medialogiabot",
		"monitage",
		"monitis",
		"monitor/webpagetest",
		"monitoring360",
		"monsidobot",
		"monspark/",
		"montastic-monitor",
		"netumo",
		"netvigie",
		"newrelicbot",
		"nixstatsbot",
		"nixstatsbot/1.1",
		"nodeping",
		"ohdear.app",
		"onetrust",
		"onlineornot",
		"outsellurlvalidator",
		"panopta",
		"parsely.com",
		"pingping.io/",
		"prtgcloudbot",
		"pulsetic.com",
		"rackspace monitoring",
		"retrolistecom/",
		"rigor",
		"robinbot",
		"ruxitsynthetic",
		"sebot-wa",
		"sentryuptimebot",
		"sequelwp",
		"server density",
		"site24x7",
		"siteuptime",
		"solarwinds",
		"spectate",
		"splunk synthetics",
		"ssl labs",
		"stape",
		"statuscake",
		"surdotlybot",
		"swifteqlinkchecker",
		"trendictionbot",
		"updown.io",
		"uptime-kuma",
		"uptime/",
		"uptimebot/1",
		"uptimemonitoring",
		"uptimerobot",
		"uptrends",
		"w3c-mobileok",
		"w3c_css_validator",
		"w3c_i18n-checker",
		"w3c_unicorn",
		"w3c_validator",
		"watchbot",
		"websiteops",
		"websitepulse checker",
		"webstatus247",
		"wknd-bot",
		"wormlybot",
		"wpmu dev broken link checker",
		"wpmudev",
		"wpumbrella",
		"www.getuptime.co",
		"www.uptimia.com",
		"xenu link sleuth",
		"zabbix",
	],
	OTHER: [
		"007ac9 crawler",
		"2ip bot",
		"360spider",
		"a6-indexer",
		"aasa-bot/",
		"aboundex",
		"acapbot",
		"acoonbot",
		"adbeat_bot",
		"admantx",
		"adscanner",
		"adstxtcrawler",
		"advbot",
		"alphabot",
		"amazon cloudfront",
		"anderspinkbot",
		"antibot",
		"anyevent",
		"apercite",
		"arabot",
		"aspiegelbot",
		"authory/",
		"awariobot",
		"awariosmartbot",
		"awesomecrawler",
		"b2b bot",
		"backlinkcrawler",
		"baidu-yunguance",
		"bdcbot",
		"behloolbot",
		"betabot",
		"bidswitchbot",
		"biglotron",
		"binlar",
		"blingerp",
		"blogmurabot",
		"blp_bbot",
		"bomborabot",
		"boxcarbot",
		"brainobot",
		"brandonbot",
		"btwebclient",
		"bublupbot",
		"buzzbot",
		"capsulechecker",
		"careerbot",
		"cc metadata scaper",
		"centcombot",
		"centurybot",
		"cincraw",
		"citeseerxbot",
		"citoid/wmf",
		"clickagy",
		"cloudflare-csup",
		"cloudflare-validator",
		"coccoc",
		"cocolyzebot",
		"companybook-crawler",
		"content crawler spider",
		"contextad bot",
		"convera",
		"crawlyprojectcrawler",
		"criteobot",
		"criticalcss.com/",
		"crystalsemanticsbot",
		"cutbot",
		"cxensebot",
		"cyberpatrol",
		"datafeedwatch",
		"datagnionbot",
		"datanyze",
		"deepnoc",
		"digincore bot",
		"discobot",
		"dnyzbot",
		"domain re-animator bot",
		"domaincrawler",
		"domainstatsbot",
		"dragonbot",
		"drupact",
		"easybill-importmanager",
		"ec2linkfinder",
		"edisterbot",
		"electricmonk",
		"elisabot",
		"epicbot",
		"eright",
		"evc-batch",
		"exabot",
		"expanse",
		"experibot",
		"extlinksbot",
		"eyeotabot",
		"ezooms",
		"fast enterprise crawler",
		"fast-webcrawler",
		"fedoraplanet",
		"femtosearchbot",
		"fever",
		"finditanswersbot",
		"findthatfile",
		"findxbot",
		"flamingo_searchengine",
		"fluffy",
		"fr-crawler",
		"friendica",
		"fuelbot",
		"fyrebot",
		"g2 web services",
		"garlikcrawler",
		"genieo",
		"gingercrawler",
		"gnam gnam spider",
		"gnowitnewsbot",
		"google-physicalweb",
		"google-xrawler",
		"grobbot",
		"gslfbot",
		"gwene",
		"helloworkjobpostingbot",
		"hifibot",
		"hstspreload-bot",
		"httrack",
		"hubspot crawler",
		"hypestat",
		"ia_archiver",
		"ichiro",
		"imrbot",
		"indeedbot",
		"inetdex-bot",
		"infoobot",
		"instapaper",
		"instapaper/4.0",
		"integromedb",
		"intelium_bot",
		"interfaxscanbot",
		"internetmeasurement",
		"ioncrawl",
		"ips-agent",
		"iskanie",
		"istellabot",
		"it2media-domain-crawler",
		"jamie's spider",
		"jetslide",
		"jobboersebot",
		"jooblebot",
		"jpg-newsbot",
		"jugendschutzprogramm-crawler",
		"jyxobot",
		"k7mlwcbot",
		"kemvibot",
		"komodiabot",
		"kosmiobot",
		"kstandbot",
		"landau-media-spider",
		"laserlikebot",
		"lb-spider",
		"lightspeedsystemscrawler",
		"linkapediabot",
		"linkdex",
		"linkisbot",
		"lipperhey",
		"lssbot",
		"lssrocketcrawler",
		"ltx71",
		"luminator-robots",
		"mappydata",
		"mauibot",
		"megaindex",
		"meltwaternews",
		"memorybot",
		"metajobbot",
		"metauri",
		"mindupbot",
		"mlbot",
		"moodlebot",
		"moreover",
		"msrbot",
		"mtrobot",
		"muckrack",
		"multiviewbot",
		"nerdybot",
		"netcraftsurveyagent",
		"netresearchserver",
		"netsystemsresearch",
		"netvibes",
		"newsharecounts",
		"nextcloud",
		"niki-bot",
		"nimbostratus-bot",
		"ninja bot",
		"nuzzel",
		"ocarinabot",
		"opengraphcheck",
		"openhosebot",
		"openindexspider",
		"outclicksbot",
		"page2rss",
		"pagething",
		"pandalytics",
		"panscient",
		"paperlibot",
		"phxbot",
		"postrank",
		"privacyawarebot",
		"proximic",
		"psbot",
		"pulsepoint",
		"purebot",
		"pwabuilderhttpagent",
		"rakutenusabot-image",
		"rankactivelinkbot",
		"regionstuttgartbot",
		"retool/",
		"retrevopageanalyzer",
		"reverseengineeringbot",
		"ridderbot",
		"rivva",
		"rytebot",
		"sbl-bot",
		"scoutjet",
		"scraping@nytimes.com",
		"scribdbot",
		"seekbot",
		"seewithkids",
		"semanticbot",
		"senutobot",
		"seokicks",
		"seolizer",
		"seoscanners",
		"serverhunterspider",
		"simplecrawler",
		"sitebot",
		"sitecheckerbotcrawler",
		"skroutz imagebot",
		"smtbot",
		"socialrankiobot",
		"sogou",
		"sora pos",
		"spbot",
		"statistikaustria",
		"summify",
		"surveybot",
		"swimgbot",
		"sysomos",
		"t3versionsbot",
		"tagoobot",
		"tangibleebot",
		"termlybot",
		"thinklab",
		"tigerbot",
		"tineye",
		"tombapublicwebcrawler",
		"toplistbot",
		"toutiaospider",
		"tracemyfile",
		"trove",
		"trovitbot",
		"tweetmemebot",
		"twengabot",
		"twingly",
		"twurly",
		"um-ln",
		"upflow",
		"urlappendbot",
		"usinenouvellecrawler",
		"vebidoobot",
		"veoozbot",
		"vercelbot",
		"virustotal",
		"vkrobot",
		"vkshare",
		"voilabot",
		"voluumdsp-content-bot",
		"vuhuvbot",
		"wbsearchbot",
		"webcompanycrawler",
		"webdatastats",
		"webmon",
		"wesee:search",
		"wocbot",
		"woobot",
		"wordpress/",
		"wordupinfosearch",
		"woriobot",
		"wotbox",
		"xovibot",
		"xy-archive-compliance",
		"y!j",
		"yanga",
		"yellowbrandprotectionbot",
		"yeti",
		"yisouspider",
		"yoozbot",
		"zenback bot",
		"zoombot",
		"zoterotranslationserver/wmf",
	],
	SCRAPER: [
		"aiohttp",
		"appengine-google",
		"automatonheadlesschrome",
		"axios",
		"bitbot",
		"coda-server-fetcher",
		"crawler4j",
		"go-http-client",
		"gowikibot",
		"headlesschrome",
		"http_get",
		"httpunit",
		"httpurlconnection",
		"httpx",
		"jetty",
		"libwww-perl",
		"metainspector",
		"node-fetch",
		"okhttp",
		"pcore-http",
		"phantomjs",
		"phpcrawl",
		"playwright",
		"puppeteer",
		"python-opengraph",
		"python-requests",
		"python-urllib",
		"scrapy",
		"simplepie",
		"simplescraper",
		"snacktory",
	],
	SEARCH_ENGINE: [
		"(dbot)",
		"alexandriaorgbot",
		"algolia crawler",
		"allafrica",
		"baidu-ads",
		"baiduspider",
		"bingbot",
		"bingbot/",
		"coccocbot",
		"coveobot",
		"crawler.freespoke.com",
		"crawlson/",
		"dataprovider",
		"daum/4.1",
		"duckduckbot",
		"duckduckgo-favicons-bot",
		"funnelback",
		"geedobot",
		"geedoproductsearch",
		"gigabot",
		"googlebot-ia/",
		"googlebot-image",
		"googlebot-mobile",
		"googlebot-news",
		"googlebot-video",
		"googlebot/",
		"http://yandex.com/bots",
		"hype machine",
		"iboubot",
		"j-dlc/",
		"jobswithgptcom",
		"kagibot/",
		"level9searchbot/",
		"linespider",
		"linguee bot",
		"magibot",
		"mojeekbot",
		"mrgbot/",
		"msnbot/",
		"neevabot",
		"newsnow",
		"notabot",
		"officestorebot",
		"piplbot",
		"potions/",
		"qwantbot",
		"qwantify",
		"safesearch microdata crawler",
		"search.marginalia.nu",
		"seekport",
		"seekportbot",
		"seznambot",
		"sitesearch360",
		"slurp",
		"smtnetpmbot/",
		"speedy",
		"stractbot",
		"teoma",
		"terracotta",
		"wellknownbot",
		"yacybot",
		"yahoo! slurp",
		"yeti/",
		"youbot",
		"zhanzhang.toutiao.com",
		"zoominfobot",
		"zumbot",
	],
	SECURITY: [
		"36b1546a5700e52eb2972b3f92b314fa",
		"bushbaby/",
		"certchief/",
		"cf-qualys-scanner",
		"compatible; detectify",
		"cookie-maestro",
		"cookiebot",
		"cookiehub",
		"cookieyesbot",
		"cybaabot",
		"dratabot",
		"fastdast",
		"google-inspectiontool",
		"google-safety",
		"google-site-verification",
		"google-trust-services",
		"https://sentry.io",
		"https://www.letsencrypt.org",
		"jumio",
		"legalmonster",
		"netcraft",
		"okx-dolphin-crawler",
		"projectshield-urlcheck",
		"reward-gateway",
		"sansec security monitor",
		"securityheaders",
		"sitelockspider",
		"smarshbot",
		"sucuri",
		"twinwavescanner",
		"verispider",
		"wtotem",
	],
	SEO_TOOL: [
		"aa/1.0",
		"addsearchbot",
		"addthis",
		"ahrefsbot",
		"ahrefssiteaudit",
		"attracta",
		"barkrowler/",
		"blexbot",
		"botify",
		"caliperbot",
		"caliperbot/1.0",
		"check_http",
		"chrome-lighthouse",
		"clearscopebot/",
		"cloudflare custom hostname verification",
		"cloudflare speedtest",
		"cloudflare stream webhook",
		"cloudflare-healthchecks",
		"cloudflare-prefetch",
		"cloudflare-purge/",
		"cloudflare-ssldetector",
		"cloudflare-traffic-manager",
		"collapsify/",
		"cookiehubscan",
		"cxensebot/",
		"dareboost",
		"dataforseobot",
		"dcrawl",
		"digicert dcv",
		"digicert dcv bot",
		"dotbot",
		"dubbotbot",
		"gigablast",
		"google-adwords-express",
		"google-adwords-instant",
		"google-structured-data-testing-tool",
		"googleassociationservice",
		"http banner detection",
		"http://www.ezoic.com/bot.html",
		"huckabot/",
		"j-brw",
		"j-brw/",
		"james bot",
		"l9explore",
		"linkcheck by siteimprove",
		"linkchecker.pro",
		"marketgoo",
		"minicrawler",
		"mj12bot",
		"nitro-",
		"nmap scripting engine",
		"nutch",
		"online-webceo-bot",
		"prerender",
		"revvimgort",
		"rogerbot",
		"rogerbot-crawler",
		"rsiteauditor",
		"screaming frog seo spider",
		"searchatlas bot",
		"semrushbot-ba",
		"semrushbot-sa",
		"semrushbot-si",
		"semrushbot/",
		"semrushbot;",
		"seo-audit-check-bot",
		"seo4ajax.com",
		"seobilitybot",
		"serankingbacklinksbot",
		"serpstatbot",
		"siteauditbot",
		"sitebulb",
		"sitecheck-sitecrawl",
		"storebot-google",
		"summalybot",
		"trellis-services",
		"w3c-checklink",
		"www.oncrawl.com",
		"zgrab",
	],
	SOCIAL_MEDIA: [
		"archivebot",
		"bingpreview",
		"bitlybot",
		"bluesky/",
		"bufferlinkpreviewbot",
		"digg deeper",
		"discordbot",
		"discordbot/",
		"embedly",
		"everyonesocialbot",
		"facebookexternalhit",
		"facebot",
		"fastmailua",
		"fedica",
		"flipboardproxy",
		"google favicon",
		"google web preview",
		"google-pagerenderer",
		"googleimageproxy",
		"groupmebot",
		"hey.com/imageproxy",
		"https://iframely.com/docs/about",
		"hubspot page fetcher",
		"iframely",
		"kakaotalk-scrap",
		"keybasebot",
		"lemmy",
		"linkarchiver",
		"linkedinbot",
		"linksindexerbot",
		"loomlybot",
		"mail.ru_bot",
		"mastodon",
		"meta-webindexer/1.1",
		"microsoftpreview/",
		"neticle crawler",
		"odklbot/",
		"opengraph.io/",
		"orlo-linkpreview/",
		"pressenginebot",
		"redditbot",
		"shortwave image fetcher",
		"skypeuripreview",
		"slack-imgproxy",
		"slackbot",
		"snap url preview service",
		"steamchat",
		"synapse",
		"telegrambot",
		"trendsmapresolver",
		"tumblr/",
		"tweetedtimes",
		"twitterbot",
		"twitterbot/",
		"vercel-screenshot",
		"viber",
		"whatsapp",
		"wordcountbot",
		"yahoo link preview",
		"yahoocachesystem",
		"yahoomailproxy",
	],
	WEBHOOK: [
		"2checkout",
		"adyen",
		"adyen httpclient",
		"aftership magento-2 connector",
		"akismet",
		"apis-google",
		"bitbucket-webhooks",
		"chargebee",
		"cron-job.org",
		"easycron/",
		"ecurly webhook",
		"exodusmovement",
		"gopay",
		"indy library",
		"integromat",
		"mainwp/",
		"make/production",
		"managewp",
		"metorik",
		"modularconnector/",
		"mollie http client/",
		"omnisend",
		"paddle",
		"paypal",
		"polar\\.sh webhooks",
		"printfriendly.com",
		"razorpay",
		"sender-9ymgn",
		"sendgrid event api",
		"shopify-captain-hook",
		"slackbot 1.0",
		"snipcart/1.0",
		"sparkpost",
		"sparkshipping",
		"stripe/1.0",
		"stripebot",
		"trustly/",
		"twilioproxy/",
		"umbrella bot",
		"vaultpress",
		"weipay-webhooks",
		"wjhro/1.0",
		"wp time capsule api/",
		"yokoygroupag/",
		"zapier",
		"zendesk webhook",
	],
};

export const UA_REGEX: Record<string, RegExp[]> = {
	ACADEMIC: [/Domains Project\//i, /^LCC/i],
	ADVERTISING: [
		/Adagiobot\//i,
		/AdsBot-Google([^-]|$)/i,
		/AmazonAdBot\//i,
		/Mediapartners \(Googlebot\)/i,
		/Quantcastbot\//i,
		/meta-externalads\//i,
	],
	AI_CRAWLER: [
		/AI2Bot\s/i,
		/Diffbot\//i,
		/Face(book){0,1}[Bb]ot/i,
		/Gluten Free Crawler\//i,
		/Perplexity-User\//i,
		/PerplexityBot\//i,
		/SBIntuitionsBot\//i,
		/[Mm]eta-[Ee]xternal[Aa]gent/i,
		/[cC]laude(?:[bB]ot|-[Ww]eb)/i,
		/collection@infegy\.com/i,
	],
	ARCHIVER: [/CCBot\//i, /archive\.org_bot/i, /web-archive-net\.com\.bot/i],
	FEED_FETCHER: [
		/BlogTraffic\/\d\.\d+ Feed-Fetcher/i,
		/Miniflux\//i,
		/i[Tt][Mm][Ss]/i,
		/rssbot\//i,
		/startmebot\//i,
		/theoldreader\.com/i,
	],
	MONITORING: [
		/(^| )sentry\//i,
		/CensysInspect\//i,
		/Checkly\//i,
		/Datadog\/{0,1}Synthetics/i,
		/Hydrozen\.io\//i,
		/NewRelicbot\//i,
		/SentryUptimeBot\/1\.0/i,
		/Uptimebot\.org/i,
		/Validator\.nu/i,
		/[pP]ingdom/i,
		/https:\/\/developers\.cloudflare\.com\/security-center\//i,
		/www\.uptime\.com/i,
	],
	OTHER: [
		/2ip\.ru/i,
		/BLEXBot\//i,
		/Bark[rR]owler/i,
		/BitSightBot\//i,
		/Bot\.AraTurka\.com/i,
		/Buck\//i,
		/CheckMarkNetwork\//i,
		/Cliqzbot\//i,
		/Dataprovider\.com/i,
		/Daum\//i,
		/DeuSu\//i,
		/Fetch\//i,
		/GroupHigh\//i,
		/ICBot\//i,
		/Livelap[bB]ot/i,
		/Mail\.RU_Bot/i,
		/MixnodeCache\//i,
		/NING\//i,
		/NerdByNature\.Bot/i,
		/OdklBot\//i,
		/OrangeBot\//i,
		/PR-CY\.RU/i,
		/Siteimprove\.com/i,
		/Streamline3Bot\//i,
		/Traackr\.com/i,
		/Vigil\//i,
		/WordPress\//i,
		/YaK\//i,
		/ZuperlistBot\//i,
		/[Cc]urebot/i,
		/^BW\//i,
		/bnf\.fr_bot/i,
		/bot-pge\.chlooe\.com/i,
		/e\.ventures Investment Crawler/i,
		/europarchive\.org/i,
		/ev-crawler\//i,
		/filterdb\.iss\.net\/crawler/i,
		/g00g1e\.net/i,
		/grub\.org/i,
		/hyscore\.io/i,
		/ip-web-crawler\.com/i,
		/sempi\.tech/i,
		/seostar\.co/i,
		/serpstatbot\//i,
		/siteexplorer\.info/i,
		/woorankreview\//i,
	],
	SCRAPER: [
		/AHC\//i,
		/PostmanRuntime\//i,
		/Stripebot\//i,
		/[wW]get/i,
		/^Apache-HttpClient/i,
		/^PHP-Curl-Class/i,
		/^curl/i,
		/newspaper\//i,
		/sindresorhus\/got/i,
	],
	SEARCH_ENGINE: [
		/Algolia Crawler\//i,
		/Googlebot\//i,
		/MojeekBot\//i,
		/YandexRenderResourcesBot\//i,
		/search\.marginalia\.nu/i,
		/webzio\s/i,
		/yandex\.com\/bots/i,
	],
	SEO_TOOL: [
		/(^| )PTST\//i,
		/(sistrix|SISTRIX) [cC]rawler/i,
		/AhrefsBot\//i,
		/AhrefsSiteAudit\//i,
		/OnCrawl\//i,
		/S[eE][mM]rushBot/i,
	],
	SOCIAL_MEDIA: [
		/BingPreview\//i,
		/MicrosoftPreview\//i,
		/PagePeeker\//i,
		/Pinterest(bot)?\//i,
		/Valve\/Steam/i,
		/developers\.google\.com\/\+\/web\/snippet/i,
		/facebookcatalog\//i,
		/pinterest\.com\/bot/i,
	],
	WEBHOOK: [/Stripe\//i],
};

export const UA_BOT_NAMES: Record<string, string> = {
	"(dbot)": "Mars Finder",
	"007ac9 crawler": "sistrix-007ac9-crawler",
	"2checkout": "2checkout",
	"2ip bot": "twoip-crawler",
	"360spider": "haosou-crawler",
	"36b1546a5700e52eb2972b3f92b314fa": "Blockaid",
	"4f.at/crawler": "foureff",
	"a patent crawler": "epfl-crawler",
	"a360-search": "Area 360",
	"a6-indexer": "a6corp-crawler",
	"aa/1.0": "Agency Analytics Crawler",
	"aasa-bot/": "Apple App Site Association",
	aboundex: "aboundex-crawler",
	academicbotrtu: "academicbot-rtu",
	acapbot: "acapbot",
	accessiblewebbot: "Accessible Web Bot",
	accessstatus: "AccessStatus",
	acoonbot: "acoon-crawler",
	activecomply: "ActiveComply Bot",
	adagiobot: "Adagio Bot",
	adbeat_bot: "adbeat-crawler",
	addsearchbot: "AddSearchBot",
	addthis: "AddThis",
	adidxbot: "Bing Ads",
	admantx: "admantx-crawler",
	"adpresearchbot/": "payroll-bot",
	"adsbot-google": "Google AdsBot",
	"adsbot-google-mobile": "google-adsbot-mobile",
	adscanner: "adscanner-crawler",
	adstxtcrawler: "adstxtcrawler",
	advbot: "advbot-crawler",
	adyen: "Adyen",
	"adyen httpclient": "adyen-webhook",
	"aftership magento-2 connector": "AfterShip Magento 2 Connector",
	ahrefsbot: "AhrefsBot",
	ahrefssiteaudit: "Ahrefs Site Audit",
	"ai2bot-dolma": "ai2-crawler-dolma",
	aihitbot: "aihit-crawler",
	aiohttp: "python-aiohttp",
	aisearchbot: "ai-search-bot",
	akismet: "Akismet",
	alertsite: "Alertsite by Smartbear",
	alexandriaorgbot: "alexandria-crawler",
	"algolia crawler": "Algolia",
	allafrica: "All Africa Crawler",
	alphabot: "alphaseobot-crawler",
	"amazon cloudfront": "amazon-cloudfront",
	"amazon route 53 health check service": "amazon-route53-health-check",
	"amazon-kendra-": "Amazon Kendra",
	amazonadbot: "Amazon AdBot",
	amazonbot: "Amazonbot",
	amazonbuyforme: "Amazon Buy For Me",
	"anchor browser": "Anchor Browser",
	anderspinkbot: "anderspink-crawler",
	anomura: "Direqt Anomura",
	antibot: "antibot",
	anyevent: "schmorp-crawler",
	apercite: "apercite-crawler",
	apifywebsitecontentcrawler: "Apify Website Content Crawler",
	"apis-google": "Google API",
	"appengine-google": "google-appengine",
	appinsights: "azure-app-insights",
	applebot: "Applebot",
	arabot: "ara-crawler",
	"archive-it": "Internet Archive - Archive-It",
	"archive.org_bot": "Internet Archive",
	archivebot: "irc-archivebot",
	"arquivo-web-crawler": "Arquivo Web Crawler",
	"artemis web reader/": "Artemis Web Reader",
	aspiegelbot: "aspiegel-crawler",
	"atlassian-bot": "atlassian-bot",
	"atom feed robot": "rssmicro-feedfetcher",
	attracta: "Attracta",
	"audisto crawler": "Audisto Crawler",
	"authory/": "Authory",
	automatonheadlesschrome: "Automaton",
	awario: "AwarioSmartBot",
	awariobot: "awario-crawler",
	awariorssbot: "awario-crawler-rss",
	awariosmartbot: "awario-crawler-smart",
	awesomecrawler: "awesomecrawler",
	axios: "javascript-axios",
	"b2b bot": "b2bbot",
	backlinkcrawler: "backlinktest-crawler",
	"baidu-ads": "Baidu ADS Server Proxy",
	"baidu-yunguance": "baidu-cloud-watch",
	baiduspider: "Baiduspider",
	"barkrowler/": "Barkrowler",
	bazqux: "Bazqux",
	bdcbot: "bigdatacorp-crawler",
	behloolbot: "webeaver-crawler",
	bestchange: "BestChange Bot",
	betabot: "betabot",
	"better stack": "betterstack-monitor",
	"better uptime bot": "Better Uptime",
	bidswitchbot: "bidswitch-crawler",
	biglotron: "biglotron",
	bigscootsmonitor: "BigScootsMonitor",
	"bigsur.ai": "Big Sur AI",
	bigupdatabot: "BigUpData Bot",
	bingbot: "bing-crawler",
	"bingbot/": "BingBot",
	bingpreview: "Bing Preview",
	binlar: "binlar",
	bitbot: "python-bitbot",
	"bitbucket-webhooks": "Bitbucket",
	bitlybot: "bitly-crawler",
	blackboard: "blackboard-crawler",
	blexbot: "BLEXBot",
	blingerp: "Bling ERP",
	blogmurabot: "blogmura-crawler",
	blogtrottr: "Blogtrottr",
	"blogvault/": "BlogVault",
	blp_bbot: "blp-bbot",
	"bluesky/": "Bluesky Link Preview Service",
	"bnf.fr_bot": "Bibliotheque Nacional de France Crawler",
	"boardgameprices bot": "BoardGamePrices Bot",
	bomborabot: "bombora-crawler",
	botify: "Botify",
	boxcarbot: "boxcar-crawler",
	brainobot: "brainobot",
	brandonbot: "brandonmedia-crawler",
	brandverity: "brandverity-crawler",
	bravebot: "Bravebot",
	"brightedge crawler": "BrightEdge Bot",
	btwebclient: "utorrent-crawler",
	bubing: "law-unimi-crawler",
	bublupbot: "bublup-crawler",
	bufferlinkpreviewbot: "Buffer Link Preview Bot",
	bugsnag: "BugsNag",
	"bushbaby/": "Bushbaby",
	buttondown: "Buttondown RSS-Feed-Parser",
	buzzbot: "buzzstream-crawler",
	bytespider: "bytedance-crawler",
	caliperbot: "conductor-crawler",
	"caliperbot/1.0": "CaliberBot",
	capitalonebot: "Capital One Bot",
	capsulechecker: "capsulink-crawler",
	careerbot: "careerx-crawler",
	catchpoint: "catchpoint",
	"cc metadata scaper": "creativecommons-crawler",
	ccbot: "commoncrawl-crawler",
	centcombot: "MelonMesa Bot",
	centurybot: "centurybot",
	"certchief/": "Cert Chief",
	"cf-qualys-scanner": "Qualys",
	changedetection: "changedetection-crawler",
	"channable/importer": "Channable",
	channel3bot: "Channel3Bot",
	chargebee: "ChargeBee",
	"chatgpt-user": "ChatGPT-User",
	check_http: "nagios-check-http",
	checkly: "Checkly Bot",
	"chrome-lighthouse": "Chrome-Lighthouse",
	cincraw: "cincrawdata-crawler",
	"cispa webcrawler": "cispa-crawler",
	citeseerxbot: "citeseerx-crawler",
	citibotsitecrawler: "CitibotSiteCrawler",
	"citoid/wmf": "WMF Citoid",
	"clearscopebot/": "ClearscopeBot",
	cledarabot: "Cledara SaaS Management Agent",
	clickagy: "clickagy-crawler",
	"clickagy intelligence bot v2": "Clickagy",
	"cloudflare custom hostname verification":
		"Cloudflare Custom Hostname Verification",
	"cloudflare speedtest": "Cloudflare SpeedTest",
	"cloudflare stream webhook": "Cloudflare Stream Webhook",
	"cloudflare-ai-search": "AI Search",
	"cloudflare-alwaysonline": "cloudflare-archiver",
	"cloudflare-csup": "Cloudflare CSUP",
	"cloudflare-healthchecks": "Cloudflare Healthchecks",
	"cloudflare-prefetch": "Cloudflare Prefetch",
	"cloudflare-purge/": "Cloudflare Purge",
	"cloudflare-ssldetector": "Cloudflare SSLDetector",
	"cloudflare-traffic-manager": "Cloudflare-Traffic-Manager",
	"cloudflare-validator": "Cloudflare Validator",
	"cloudflarebrowserrenderingcrawler/1.0": "Cloudflare Crawler",
	cloudflarediagnostics: "Cloudflare Diagnostics",
	cloudtrellis: "Cloudtrellis",
	cloudvertexbot: "Google-CloudVertexBot",
	"cludo.com": "Cludo",
	coccoc: "coccoc-crawler",
	coccocbot: "Cốc Cốc",
	cocolyzebot: "cocolyze-crawler",
	"coda-server-fetcher": "coda-server-fetcher",
	"cohere-ai": "cohere-crawler",
	"collapsify/": "Cloudflare Custom Error Page Crawler",
	"companybook-crawler": "companybook-crawler",
	"compatible; detectify": "Detectify",
	"compatible; proximic": "Proximic",
	"content crawler spider": "content-crawler-spider",
	contentking: "ContentKing",
	"contextad bot": "contextad-crawler",
	contextualbot: "ContextualBot",
	contxbot: "Amazon Contxbot",
	convera: "convera-crawler",
	"convermax/": "ConvermaxBot",
	"cookie-maestro": "cookie maestro",
	cookiebot: "Cookiebot",
	cookiehub: "Cookie Hub",
	cookiehubscan: "cookiehub-scan",
	cookieyesbot: "CookieYesBot",
	"cotoyogi/": "Cotoyogi",
	coveobot: "Coveo Bot",
	"cozi-icalendar-feedreader": "OurFamilyWizard",
	"crawler.freespoke.com": "Freespoke",
	crawler4j: "java-crawler4j",
	"crawlson/": "Crawlson",
	crawlyprojectcrawler: "digitaldragon-crawler",
	"crazy egg": "Crazy Egg Bot",
	criteobot: "criteo-crawler",
	"criteobot/": "CriteoBot",
	"criticalcss.com/": "Critical CSS Bot",
	"cron-job.org": "cron-job.org",
	crunchbot: "leadcrunch-crawler",
	crystalsemanticsbot: "crystalsemantics-crawler",
	"curl/7.58.0-dev": "Thousand Eyes Cloud Agent",
	"curly-": "Cloudflare Observatory Curly",
	cutbot: "cutbot-crawler",
	cxensebot: "cxense-crawler",
	"cxensebot/": "Cxense",
	cybaabot: "Cybaa Bot",
	cyberpatrol: "cyberpatrol-crawler",
	dareboost: "dareboost-crawler",
	datadog: "Synthetic Bot",
	datafeedwatch: "datafeedwatch-crawler",
	dataforseobot: "DataForSEO Bot",
	datagnionbot: "datagnion-crawler",
	datanyze: "datanyze-crawler",
	dataprovider: "Dataprovider.com",
	"daum/4.1": "Daum",
	dcrawl: "dcrawl",
	deadlinkchecker: "deadlinkchecker",
	deepnoc: "deepnoc-crawler",
	devin: "Devin",
	"digg deeper": "digg-crawler",
	"digicert dcv": "Cloudflare Digicert DCV",
	"digicert dcv bot": "DigiCert DCV",
	"digincore bot": "digincore-crawler",
	discobot: "discoveryengine-crawler",
	discordbot: "discord-crawler",
	"discordbot/": "discordBot",
	disqus: "disqus-crawler",
	"dlc/": "Dr. Link Check",
	dmbrowser: "Doctom Monitor",
	dnyzbot: "dnyz-crawler",
	"domain re-animator bot": "domainreanimator-crawler",
	domaincrawler: "domaincrawler-crawler",
	domainstatsbot: "domainstats-crawler",
	dotbot: "Moz dotbot",
	dragonbot: "dragonmetrics-crawler",
	dratabot: "Drata Autopilot",
	drupact: "arocom-crawler",
	dubbotbot: "dubbot-crawler",
	duckassistbot: "DuckAssistbot",
	duckduckbot: "DuckDuckBot",
	"duckduckgo-favicons-bot": "duckduckgo-crawler-favicons",
	"easybill-importmanager": "EasyBill Import Manager",
	"easycron/": "EasyCron",
	easyscan: "EasyScan",
	ec2linkfinder: "ec2linkfinder",
	"ecurly webhook": "Recurly Webhooks",
	edisterbot: "edister-crawler",
	electricmonk: "duedil-crawler",
	elisabot: "elisabot",
	"elmahio-uptimebot": "elmah.io Uptime Monitoring",
	embedly: "embedly-crawler",
	"emoneybot/": "eMoney Advisor",
	epicbot: "epictions-crawler",
	"epivozcrawler/": "Epivoz Crawler",
	"erepublik.tools": "eRepublik.tools",
	eright: "eright-crawler",
	"evc-batch": "eventures-crawler-batch",
	everyonesocialbot: "everyonesocial-crawler",
	"evouptimebot/": "EvoUptimeBot",
	exabot: "amazon-alexa-crawler",
	exodusmovement: "Exodus",
	expanse: "paloaltonetworks-crawler",
	experibot: "experibot-crawler",
	extlinksbot: "extlinks-crawler",
	eyeotabot: "eyeota-crawler",
	ezid: "ezid-crawler",
	ezooms: "dotnetdotcom-crawler",
	facebookexternalhit: "FacebookExternalHit",
	facebot: "imessage-preview",
	factset_spyderbot: "Factset_spyderbot",
	"fast enterprise crawler": "fast-crawler-enterprise",
	"fast-webcrawler": "fast-crawler",
	fastdast: "Black Duck Fast Dynamic",
	fastmailua: "Fastmail Bot",
	"fdl stats bot": "FDL Stats Bots",
	fedica: "Fedicabot",
	fedoraplanet: "fedoraplanet-crawler",
	fedreporterdatabot: "FedReporter Bot for FFIEC",
	feedbin: "Feedbin",
	feedbot: "wordpress-crawler-rss",
	"feeder.co": "Feeder",
	"feedfetcher-google": "google-feedfetcher",
	feedly: "feedly-feedfetcher",
	"feedly/1": "Feedly",
	feedspot: "feedspot-feedfetcher",
	feedvalidator: "w3c-validator-feed",
	"feedwind/": "FeedWind Crawler",
	femtosearchbot: "femtosearch-crawler",
	fever: "feedafever-crawler",
	finditanswersbot: "itinfluentials-crawler",
	findlink: "leipzig-findlinks",
	findthatfile: "findthatfile-crawler",
	findxbot: "privacore-crawler",
	flamingo_searchengine: "flamingosearch-crawler",
	flipboardproxy: "FlipboardProxy",
	flipboardrss: "FlipboardRSS",
	flockwp: "FlockWP",
	fluffy: "fluffy",
	"follow.it": "FIT Feeds Fetcher",
	foregenix: "Foregenix ThreatView/WebScan",
	"fr-crawler": "fr-crawler",
	"freewebmonitoring sitechecker": "freewebmonitoring-monitor",
	freshping: "Freshping",
	freshpingbot: "freshworks-monitor",
	freshrss: "freshrss-feedfetcher",
	friendica: "hoyer-crawler",
	friendlycrawler: "friendlycrawler",
	fuelbot: "fuelbot",
	fullstorybot: "FullStory",
	funnelback: "Funnelback",
	fyrebot: "fyrebot",
	"g2 web services": "g2webservices-crawler",
	"g2reader-bot": "g2reader-crawler",
	garlikcrawler: "garlik-crawler",
	geedobot: "geedo-crawler",
	geedoproductsearch: "geedo-crawler-products",
	genieo: "genieo-crawler",
	"ghost inspector": "Ghost Inspector",
	gigablast: "gigablast-crawler-oss",
	gigabot: "Gigabot",
	gingercrawler: "ginger-crawler",
	"gnam gnam spider": "gnam-gnam-spider",
	gnowitnewsbot: "gnowit-crawler",
	"go-http-client": "go-http",
	"google favicon": "google-favicon",
	"google web preview": "google-preview",
	"google-ads-conversions": "google-ads-conversions",
	"google-adwords-express": "Google-AdWords-Express",
	"google-adwords-instant": "Google-Adwords-Instant",
	"google-agent": "Google-Agent",
	"google-certificates-bridge": "google-certificates-bridge",
	"google-cloudvertexbot": "google-crawler-cloudvertex",
	"google-display-ads-bot": "Google-Display-Ads-Bot",
	"google-firebase": "Google Firebase",
	"google-inspectiontool": "Google Inspection Tool",
	"google-pagerenderer": "Google Page Renderer",
	"google-physicalweb": "google-physical-web",
	"google-read-aloud": "Google Read Aloud",
	"google-safety": "Google Safety",
	"google-site-verification": "Google Site Verification",
	"google-structured-data-testing": "Google Schema Markup Testing Tool",
	"google-structured-data-testing-tool": "google-structured-data-testing-tool",
	"google-trust-services": "Google Trust Services (DCV Check)",
	"google-xrawler": "google-xrawler",
	"google.com/feedfetcher": "Google Feed Fetcher",
	googleassociationservice: "Google Digital Asset Links",
	"googlebot-ia/": "Google Scholar",
	"googlebot-image": "Google Images",
	"googlebot-mobile": "google-crawler-mobile",
	"googlebot-news": "google-crawler-news",
	"googlebot-video": "Google Videos",
	"googlebot/": "GoogleBot",
	googleimageproxy: "Google Image Proxy",
	googleother: "GoogleOther",
	googleproducer: "Google Publisher Center",
	gopay: "GoPay",
	gowikibot: "gowiki-crawler",
	gptbot: "GPTBot",
	"grafana/synthetic-monitoring": "Grafana's Synthetic Monitoring",
	grapeshotcrawler: "Grapeshot",
	grobbot: "grob-crawler",
	groovinaadsbot: "Groovinads",
	groupmebot: "groupme-crawler",
	gslfbot: "gslfbot",
	gtmetrix: "GTmetrix",
	"guestpostsbot/": "GuestpostsBot",
	gwene: "gwene-crawler",
	"haiku-searchbot": "Haiku-SearchBot",
	hatena: "Hatena",
	headlesschrome: "headless-chrome",
	helloworkjobpostingbot: "HelloWork",
	heritrix: "internetarchive-crawler-oss",
	hetrixtools: "HetrixTools",
	"hey.com/imageproxy": "HEY Email Privacy Proxy",
	hifibot: "HIFIBot",
	"honeybadger uptime check": "honeybadgerbot",
	hosttracker: "HostTracker",
	hotjar: "Hotjar",
	"hstspreload-bot": "HSTS preload bot",
	"http banner detection": "ipip-crawler",
	http_get: "http-get",
	"http://easyurl.net/monitoring": "Easydns",
	"http://www.binarycanary.com": "BinaryCanary",
	"http://www.ezoic.com/bot.html": "EzoicBot",
	"http://www.pingdom.com/": "Pingdom",
	"http://yandex.com/bots": "YandexBot",
	"https://iframely.com/docs/about": "Iframely",
	"https://sentry.io": "Sentry",
	"https://www.letsencrypt.org": "Let's Encrypt",
	"https://www.loc.gov/programs/web-archiving/for-site-owners/":
		"Library Of Congress Web Archiving",
	httpunit: "java-httpunit",
	httpurlconnection: "java-jersey",
	httpx: "python-httpx",
	httrack: "httrack",
	hubspot: "hubspot-crawler",
	"hubspot crawler": "HubSpot Crawler",
	"hubspot page fetcher": "HubSpot Page Fetcher",
	"hubspot-feedfetcher": "HubSpot Feed Fetcher",
	"huckabot/": "Huckabuy Bot",
	"hype machine": "Hype Machine",
	hypestat: "hypestat-crawler",
	ia_archiver: "ia-archiver",
	"iabot/": "InternetArchiveBot",
	"ias crawler": "integralads-crawler",
	ias_crawler: "IAS crawler",
	iaskspider: "iask-crawler",
	iboubot: "IbouBot",
	"icc-crawler": "nict-crawler",
	"icc-crawler/": "ICC Crawler",
	ichiro: "goo-crawler",
	iframely: "iframely-preview",
	ifttt: "IFTTT RSS Feed Service",
	imagesiftbot: "imagesift-crawler",
	img2dataset: "img2dataset",
	imrbot: "mignify-imrbot",
	indeedbot: "indeed-crawler",
	indeedjobbot: "IndeedJobBot",
	"indy library": "Worldline Bot",
	"inetdex-bot": "inetdex-crawler",
	infoobot: "infoo-crawler",
	innguma: "Innguma Fetcher",
	inoreader: "inoreader-aggregator",
	"inoreader.com": "Innologica",
	instapaper: "Instapaper",
	"instapaper/4.0": "Instapaper",
	integromat: "Integromat",
	integromedb: "integromedb-crawler",
	intelium_bot: "intelium-crawler",
	interactiveadvertisingbureau: "AdsTxtCrawler",
	interfaxscanbot: "scan-interfax-crawler",
	internetmeasurement: "driftnet-crawler",
	ioncrawl: "ionos-crawler",
	"ips-agent": "verisign-ips-agent",
	isdownbot: "IsDownBot",
	iskanie: "iskanie-crawler",
	istellabot: "tiscali-crawler",
	"it2media-domain-crawler": "it2media-crawler",
	"j-brw": "Yahoo Japan SEO Crawler",
	"j-brw/": "Yahoo Japan SEO Crawler",
	"j-dlc/": "Yahoo! JAPAN",
	"james bot": "cognitiveSEO Crawler",
	"jamie's spider": "jamiembrown-crawler",
	jetmon: "Jetpack",
	jetslide: "jetslide-crawler",
	jetty: "java-jetty",
	jobboersebot: "jobboerse-crawler",
	jobswithgptcom: "jobswithgptcom-bot",
	jooblebot: "jooble-crawler",
	"jpg-newsbot": "vipnytt-crawler",
	"jugendschutzprogramm-crawler": "jusprog-crawler",
	jumio: "Jumio",
	jyxobot: "jyxo-crawler",
	k7mlwcbot: "k7computing-crawler",
	"kagibot/": "Kagi Bot",
	"kakaotalk-scrap": "KakaoTalk Scrap",
	"kargobot-artemis": "KargoBot-Artemis",
	kemvibot: "kemvi-crawler",
	keybasebot: "keybase-bot",
	"kinsta-bot": "Kinsta",
	"klaviyo/1.0": "klaviyo",
	"known agent": "Known Agent",
	komodiabot: "komodia-crawler",
	kosmiobot: "kosmio-crawler",
	kstandbot: "urlclassification-crawler",
	l9explore: "l9explore",
	"landau-media-spider": "landaumedia-crawler",
	laserlikebot: "laserlike-crawler",
	"lb-spider": "lb-spider",
	legalmonster: "LegalMonster",
	leikibot: "LeikiBot",
	lemmy: "lemmy-crawler",
	"level9searchbot/": "Level9SearchBot",
	"libwww-perl": "perl-libwww",
	lightspeedsystemscrawler: "lightspeedsystems-crawler",
	linerbot: "LINER Bot",
	linespider: "Linespider",
	"linguee bot": "linguee-crawler",
	linkapediabot: "linkapedia-crawler",
	linkarchiver: "linkarchiver",
	"linkcheck by siteimprove": "LinkCheck",
	"linkchecker.pro": "LinkChecker Bot",
	linkdex: "linkdex-crawler",
	linkedinbot: "LinkedInBot",
	linkisbot: "linkis-crawler",
	linksindexerbot: "LinksIndexerBot",
	linktiger: "Link Tiger ",
	lipperhey: "lipperhey-crawler",
	"logicmonitor sitemonitor/": "logicmonitor",
	loomlybot: "Loomly Bot",
	lssbot: "lssbot",
	lssrocketcrawler: "lssbot-rocket",
	ltx71: "ltx71-crawler",
	lumar: "Deepcrawl",
	"luminator-robots": "luminator-crawler",
	macocu: "macocu-crawler",
	macrobondbot: "Macrobondbot",
	magibot: "MagiBot",
	"magnet.me-web/": "MagnetmeBot",
	"magpie-crawler": "Brandwatch",
	"mail.ru_bot": "MailRUBot",
	"mainwp/": "MainWP",
	"make/production": "Make Platform",
	managewp: "ManageWP",
	mappydata: "mappydata-crawler",
	marketgoo: "marketgoo",
	mastodon: "mastodon-crawler",
	mauibot: "mauibot",
	mavifinds: "Mavifinds Bot",
	mbcrawler: "monitorbacklinks-crawler",
	mediaboardbot: "mediaboardbot",
	medialogiabot: "Medialogia Bot",
	"mediamonitoringbot/": "MediaMonitoringBot",
	"mediapartners-google": "Google Adsense: Mediapartners-Google",
	mediatoolkitbot: "Mediatoolkitbot",
	"mediavinemetadataparser/": "Mediavine Medatada Parser",
	megaindex: "megaindex-crawler",
	meltwaternews: "meltwater-crawler",
	memorybot: "mignify-crawler",
	"meta-externalads/1.1": "Meta-ExternalAds",
	"meta-externalagent": "Meta-ExternalAgent",
	"meta-externalfetcher": "meta-crawler-user",
	"meta-externalfetcher/": "Meta-ExternalFetcher",
	"meta-webindexer/1.1": "Meta-WebIndexer",
	metainspector: "ruby-metainspector",
	metajobbot: "metajob-crawler",
	metauri: "metauri-crawler",
	metorik: "Metorik",
	mgidbot: "MgidBot",
	"microsoftpreview/": "Microsoft Preview",
	mindupbot: "datenbutler-crawler",
	minicrawler: "testomato-crawler",
	mirrorweb: "MirrorWebCrawler",
	missinglettrbot: "Missinglettr Bot",
	"mistralai-user": "MistralAI-User",
	mj12bot: "MJ12Bot",
	mlbot: "metadatalabs-crawler",
	moatbot: "moat-crawler",
	"modularconnector/": "Modular DS",
	mojeekbot: "Mojeek",
	"mollie http client/": "Mollie Bot",
	monitage: "Monitage",
	monitis: "Monitis",
	"monitor/webpagetest": "webpagetest",
	monitoring360: "360Monitoring",
	"monitorss/": "MonitoRSS",
	monsidobot: "Monsidobot",
	"monspark/": "MonSpark",
	"montastic-monitor": "MontasticMonitor",
	moodlebot: "moodle-crawler",
	moreover: "moreover-crawler",
	motominerbot: "MotoMinerBot",
	"mrgbot/": "MRGbot",
	msnbot: "msn-crawler",
	"msnbot/": "MSN",
	msrbot: "microsoft-research-crawler",
	mtrobot: "metricstools-crawler",
	muckrack: "muckrack-crawler",
	"muckrack.com": "Muck Rack Scraper",
	multiviewbot: "multiviewbot",
	"nava/": "Nava Labs ASP (Dev)",
	"naver blog rssbot": "naver-crawler-rss",
	neevabot: "Neevabot",
	nerdybot: "nerdybot-crawler",
	netarkivindsamling: "kb.dk_bot",
	netcraft: "Netcraft",
	netcraftsurveyagent: "netcraft-crawler",
	"netestate ne crawler": "netEstate Imprint Crawler",
	"neticle crawler": "neticle-crawler",
	netresearchserver: "loop-crawler",
	netsystemsresearch: "netsystemsresearch-crawler",
	netumo: "Netumo",
	netvibes: "netvibes-crawler",
	netvigie: "NETVIGIE",
	newrelicbot: "New Relic",
	newsblur: "NewsBlur",
	newsharecounts: "newsharecounts-crawler",
	newsnow: "NewsNow",
	nextcloud: "nextcloud-crawler",
	nicecrawler: "nicecrawler-archive",
	"niki-bot": "niki-bot",
	"nimbostratus-bot": "cloudsystemnetworks-crawler",
	"ninja bot": "ninjabot",
	"nitro-": "NitroBot",
	nixstatsbot: "nixstats-crawler",
	"nixstatsbot/1.1": "NixStatsMonitoringBot",
	"nmap scripting engine": "nmap",
	"node-fetch": "javascript-node-fetch",
	nodeping: "Nodeping",
	noibu: "Noibu JS Beautifier",
	noorobot: "Noorobot",
	nooshub: "Nooshub",
	nostocrawlerbot: "NostoCrawlerBot",
	notabot: "Notabot",
	notebooklm: "Google NotebookLM",
	novellum: "Novellum AI Crawl",
	ntentbot: "ntent-crawler",
	nutch: "nutch",
	nuzzel: "nuzzel-crawler",
	"oai-searchbot": "OAI-SearchBot",
	ocarinabot: "ocarinabot",
	"odklbot/": "Ozon Web Grabber",
	officestorebot: "bing-office-store",
	"ohdear.app": "Oh Dear",
	okhttp: "java-okhttp",
	"okx-dolphin-crawler": "OKX-dolphin-crawler",
	omgili: "omgili-crawler",
	omnisend: "Omnisend",
	onetrust: "Onetrust CMP Scanner",
	"online-webceo-bot": "Online Webceo Bot",
	onlineornot: "OnlineOrNot Monitor",
	"opengraph.io/": "Opengraph Bot",
	opengraphcheck: "opengraphcheck-crawler",
	openhosebot: "openhose-crawler",
	openindexspider: "openindex-crawler",
	openrss: "OpenRSS",
	"orlo-linkpreview/": "Orlo Link Preview",
	outbrain: "Outbrain",
	outclicksbot: "outclicks-crawler",
	outsellurlvalidator: "OutsellURLValidator",
	"overcast/1.0 podcast sync": "Overcast",
	paddle: "Paddle Webhooks",
	"page-preview-tool": "SalesViewerBot",
	page2rss: "page-to-rss",
	pagething: "pagething-crawler",
	pandalytics: "domainsbot-crawler",
	panopta: "Panopta",
	panscient: "panscient-crawler",
	paperlibot: "paperli-crawler",
	"parsely.com": "Parse.ly",
	paypal: "PayPal",
	"pcore-http": "perl-pcore",
	petalbot: "PetalBot",
	phantomjs: "javascript-phantom",
	phpcrawl: "php-phpcrawl",
	phxbot: "phxbot",
	"pingping.io/": "PingPing",
	"pinterest.com/": "PinterestBot",
	piplbot: "pipl-crawler",
	"pocket casts feed parser": "Pocket Casts Feed Parser",
	pocketparser: "pocket-crawler",
	"polar\\.sh webhooks": "Polar",
	postrank: "postrank-crawler",
	"potions/": "Potions",
	prerender: "prerender",
	pressenginebot: "PressEngine Bot",
	primalbot: "primal-crawler",
	"printfriendly.com": "PrintFriendly",
	privacyawarebot: "privacyaware-crawler",
	"pro-sitemaps/": "Pro Sitemaps",
	"productsup.io/crawler": "Productsup Crawler",
	"projectshield-urlcheck": "ProjectShield Url Check",
	protopage: "Protopage",
	proximic: "proximic-crawler",
	prtgcloudbot: "PaesslerCloudBot",
	psbot: "picsearch-crawler",
	pulsepoint: "pulsepoint-crawler",
	"pulsetic.com": "Pulsetic",
	purebot: "pure-crawler",
	pwabuilderhttpagent: "PWABuilder",
	"python-opengraph": "python-opengraph",
	"python-requests": "python-requests",
	"python-urllib": "python-urllib",
	qualifiedbot: "QualifiedBot",
	quantcastbot: "Quantcastbot",
	qwantbot: "Qwantbot",
	qwantify: "qwant-crawler",
	"rackspace monitoring": "Rackspace",
	"rakutenusabot-image": "Rakuten Image extraction bot",
	rankactivelinkbot: "rankactive-crawler",
	razorpay: "Razorpay Webhook",
	"readable/": "Readable",
	redditbot: "reddit-crawler",
	"reelevant/": "Reelevant",
	refindbot: "refind-crawler",
	regionstuttgartbot: "stuttgart-crawler",
	"retool/": "Retool",
	retrevopageanalyzer: "retrevo-page-analyzer",
	"retrolistecom/": "RetroListeCOM",
	reverseengineeringbot: "torus-crawler",
	revvimgort: "Revvim",
	"reward-gateway": "Reward Gateway",
	ridderbot: "ridder-crawler",
	rigor: "Splunk",
	rivva: "rivva-crawler",
	robinbot: "Robinbot",
	rogerbot: "moz-site-audit",
	"rogerbot-crawler": "Moz rogerbot",
	rsiteauditor: "DataForSEO",
	"rss2tg bot": "rss2tg_bot",
	"rssapi/": "RSS API",
	rssingbot: "rssing-crawler",
	ruxitsynthetic: "dynatrace-monitor",
	rytebot: "ryte-crawler",
	safednsbot: "safedns-crawler",
	"safesearch microdata crawler": "avira-crawler",
	"sansec security monitor": "Sansec Security Monitor",
	"sbl-bot": "softbytelabs-crawler",
	scavobot: "ScavoBot",
	"scour.ing": "Scour RSS Bot",
	scoutjet: "scoutjet-crawler",
	"scraping@nytimes.com": "New York Times Newsgathering",
	scrapy: "python-scrapy",
	"screaming frog seo spider": "screamingfrog-crawler",
	scribdbot: "scribd-crawler",
	"search.marginalia.nu": "Marginalia Search",
	searchatlas: "searchatlas-crawler",
	"searchatlas bot": "SearchAtlas Bot",
	"sebot-wa": "SE Ranking Bot",
	securityheaders: "SecurityHeaders",
	seekbot: "seekbot-crawler",
	seekport: "seekport-crawler",
	seekportbot: "Seekport",
	seewithkids: "seewithkids-crawler",
	semanticbot: "semanticaudience-crawler",
	semanticscholarbot: "semanticscholar-crawler",
	"semrushbot-ba": "SemrushBotBacklinkAudit",
	"semrushbot-ocob": "SemrushBot-OCOB",
	"semrushbot-sa": "Semrushbot",
	"semrushbot-si": "SemrushBotSI",
	"semrushbot-swa/": "SemrushBotSwa",
	"semrushbot;": "SemrushBotLinkBuilding",
	"semrushbot/": "SemrushBotBacklinks",
	"sender-9ymgn": "Svix Webhooks",
	"sendgrid event api": "SendGrid",
	sentibot: "sentione-crawler",
	sentryuptimebot: "Sentry Uptime Monitoring",
	senutobot: "senuto-crawler",
	"seo-audit-check-bot": "SEO Audit Check Bot",
	"seo4ajax.com": "seo4ajax",
	seobilitybot: "SeobilityBot",
	seokicks: "seokicks-crawler",
	seolizer: "seolizer-crawler",
	seoscanners: "seoscanners-crawler",
	sequelwp: "SequelWP",
	serankingbacklinksbot: "SERankingBacklinksBot",
	serendeputybot: "serendeputy-crawler",
	serpstatbot: "SerpstatBot",
	"server density": "Server Density",
	serverhunterspider: "ServerHunterSpider",
	seznambot: "Seznam",
	"sfdc-callout": "Salesforce",
	"shapbot/": "ShapBot",
	"shopify-captain-hook": "Shopify-Captain-Hook",
	"shortwave image fetcher": "Shortwave Image Fetcher",
	silktide: "SilktideBot",
	simplecrawler: "simple-crawler",
	simplepie: "php-simplepie",
	simplescraper: "php-simple-scraper",
	site24x7: "Site24x7",
	siteauditbot: "SiteAuditBot",
	sitebot: "sitebot-crawler",
	sitebulb: "sitebulb",
	"sitecheck-sitecrawl": "Siteimprove Crawl",
	sitecheckerbotcrawler: "sitechecker-crawler",
	sitelockspider: "SiteLock",
	sitesearch360: "SiteSearch360",
	siteuptime: "SiteUpTimeBot",
	"skroutz imagebot": "Skroutz ImageBot",
	skroutzbot: "SkroutzBot",
	skypeuripreview: "Skype",
	"slack-imgproxy": "Slack Image Proxy",
	slackbot: "slack-crawler",
	"slackbot 1.0": "Slackbot",
	slickbot: "Slickstream",
	slopsearch: "slopsearch",
	slurp: "yahoo-crawler",
	smarshbot: "SmarshBot",
	smartologybot: "SmartologyBot",
	smtbot: "similartech-crawler",
	"smtnetpmbot/": "SMTnet PM Bot",
	snacktory: "java-snacktory",
	"snap url preview service": "snap-preview",
	"snipcart/1.0": "Snipcart",
	socialrankiobot: "socialrank-crawler",
	sogou: "sogou-crawler",
	solarwinds: "SolarWinds Observability",
	sonic: "yamanalab-crawler",
	"sora pos": "Sora Caisse POS",
	sparkpost: "SparkpostBot",
	sparkshipping: "Spark Shipping",
	spbot: "seoprofiler-crawler",
	spectate: "Spectate",
	speedy: "entireweb-crawler",
	"splunk synthetics": "Splunk Synthetics",
	spyglassesbot: "Spyglasses Bot",
	"ssl labs": "Qualys SSL Scanner",
	stape: "Stape Scanner",
	statabot: "Statabot",
	statistikaustria: "StatistikAustria",
	statsdronebot: "StatsDroneBot",
	statuscake: "StatusCake",
	steamchat: "Steam Chat",
	"storebot-google": "Google StoreBot",
	storygizebot: "storygize-crawler",
	stractbot: "stract-crawler",
	"stripe/1.0": "Stripe",
	stripebot: "Stripebot",
	sucuri: "Sucuri",
	summalybot: "summaly-crawler",
	summify: "summify-crawler",
	superfeedr: "superfeedr-crawler",
	surdotlybot: "surly-crawler",
	surveybot: "domaintools-crawler",
	swifteqlinkchecker: "Swifteq Link Checker",
	swimgbot: "swimgbot",
	synapse: "synapse-crawler",
	sysomos: "sysomos-crawler",
	t3versionsbot: "t3versions-crawler",
	taboolabot: "Taboola",
	tagoobot: "tagoo-crawler",
	tangibleebot: "tangiblee-crawler",
	telegrambot: "Telegram Bot",
	teoma: "ask-crawler",
	termlybot: "Termly",
	terracotta: "Terracotta",
	thinklab: "thinklab-crawler",
	tigerbot: "tiger-crawler",
	tiktokspider: "tiktok-crawler",
	timpibot: "timpi-crawler",
	tineye: "tineye-crawler",
	"tiny tiny rss": "ttrss-feedfetcher",
	tombapublicwebcrawler: "tombascraper-crawler",
	toplistbot: "toplist-crawler",
	toutiaospider: "toutiao-crawler",
	tracemyfile: "tracemyfile-crawler",
	"trellis-services": "Trellis-Services",
	trendictionbot: "Trendiction Bot",
	trendsmapresolver: "trendsmap-crawler",
	trove: "trove-crawler",
	trovitbot: "trovit-crawler",
	"trustly/": "Trustly",
	"ttd-content": "TTD Content",
	"tumblr/": "Tumblr",
	turnitin: "TurnitinBot",
	tweetedtimes: "tweetedtimes-crawler",
	tweetmemebot: "tweetmemebot",
	twengabot: "twenga-crawler",
	"twilioproxy/": "Twilio Proxy",
	twinagent: "TwinAgent",
	twingly: "twingly-crawler",
	twinwavescanner: "Splunk Attack Analyzer",
	twitterbot: "twitter-crawler",
	"twitterbot/": "twitterbot",
	twurly: "twurly-crawler",
	"um-ln": "ubermetrics-crawler",
	"umbrella bot": "WP Umbrella Bot",
	"upday/": "upday",
	"updown.io": "UpDownBot",
	upflow: "upflow-crawler",
	"uptime-kuma": "kuma-monitor",
	"uptime/": "Uptime LLC",
	"uptimebot/1": "UptimeBot",
	uptimemonitoring: "Uptime Monitoring",
	uptimerobot: "UptimeRobot",
	uptrends: "UptrendsBot",
	urlappendbot: "profound-crawler",
	usinenouvellecrawler: "usine-nouvelle-crawler",
	"ut-dorkbot": "utexas-crawler",
	vaultpress: "VaultPress",
	vebidoobot: "vebidoo-crawler",
	velenpublicwebcrawler: "velen-crawler",
	veoozbot: "veooz-crawler",
	"vercel-screenshot": "vercel-monitor-preview",
	vercelbot: "vercel-crawler",
	verispider: "Project Honeypot",
	viber: "viber-crawler",
	videootvbot: "videootv Bot",
	virustotal: "virustotal-crawler",
	vkrobot: "vkrobot-crawler",
	vkshare: "vkshare-crawler",
	voilabot: "orange-ftgroup-crawler",
	"voluumdsp-content-bot": "codewise-crawler",
	vuhuvbot: "vuhuv-crawler",
	w3c_css_validator: "w3c-validator-css",
	"w3c_i18n-checker": "w3c-validator-i18n",
	w3c_unicorn: "w3c-validator-unified",
	w3c_validator: "w3c-validator-html",
	"w3c-checklink": "W3 Validator Services",
	"w3c-mobileok": "w3c-validator-mobile",
	w4mwnpbxf3mfabxokjrw: "Echobot Bot",
	wardbot: "WARDBot",
	watchbot: "Watchbot",
	wbsearchbot: "warebay-crawler",
	webcompanycrawler: "webcompany-crawler",
	webdatastats: "webdatastats-crawler",
	webmon: "webmon",
	websiteops: "Watchful",
	"websitepulse checker": "WebsitePulseBot",
	webspidermount: "WebSpiderMount",
	webstatus247: "Webstatus247",
	"webzio-extended": "webzio-crawler-ai",
	"weipay-webhooks": "Coinbase Webhooks",
	wellknownbot: "wellknown-crawler",
	"wesee:search": "wesee-crawler",
	whatsapp: "whatsapp-crawler",
	"wjhro/1.0": "WorldPay",
	"wknd-bot": "WkndHealthCheckBot",
	wocbot: "wocodi-crawler",
	woobot: "woorank-crawler",
	wordcountbot: "WordCountBot",
	"wordpress/": "Wordpress Namecheap",
	wordupinfosearch: "wordup-crawler",
	woriobot: "worio-crawler",
	wormlybot: "WormlyBot",
	wotbox: "wotbox-crawler",
	wovncrawler: "WOVN Crawler",
	"wp time capsule api/": "WP Time Capsule",
	"wpmu dev broken link checker": "WPMU DEV Broken Link Checker",
	wpmudev: "WPMUDEV Uptime Monitor 5.0",
	wpumbrella: "WP Umbrella",
	wtotem: "WebTotemBot",
	"www.getuptime.co": "Jagged Pixel UptimeBot",
	"www.oncrawl.com": "OnCrawl",
	"www.uptimia.com": "Uptimia",
	"xenu link sleuth": "xenu-crawler",
	xovibot: "xovibot-crawler",
	"xy-archive-compliance": "XY Archive Compliance Bot",
	"y!j": "yahoo-crawler-japan",
	"y!j-asr": "Yahoo Japan",
	"y!j-b|yj-sad": "Yahoo Japan",
	"y!j-brj/yats crawler": "Yahoo Japan",
	"y!j-bru/vsidx": "Yahoo Japan",
	"y!j-brw": "Yahoo Japan",
	"y!j-bry/yatsh crawler": "Yahoo Japan",
	"y!j-brz/yatsha crawler": "Yahoo Japan",
	"y!j-mmp/dscv": "Yahoo Japan",
	"y!j-wsc": "Yahoo Japan",
	yacybot: "yacy-crawler",
	"yahoo ad monitoring": "Yahoo Ad Monitoring",
	"yahoo link preview": "Yahoo Link Preview",
	"yahoo! slurp": "Yahoo Slurp",
	yahoocachesystem: "YahooCacheSystem",
	yahoomailproxy: "YahooMailProxy",
	yanga: "yanga-crawler",
	yellowbrandprotectionbot: "yellowbp-crawler",
	yeti: "naver-crawler",
	"yeti/": "Yeti",
	yextbot: "Yext Inc",
	"ygs-scraper-bot": "YGS Group Falconer Scraper",
	yisouspider: "yisou-crawler",
	"yj-sad": "Yahoo Japan",
	"yokoygroupag/": "Yokoy Group Webhooks",
	yoozbot: "yooz-crawler",
	youbot: "YouBot",
	zabbix: "zabbix-monitor",
	zapier: "Zapier",
	"zenback bot": "logly-crawler",
	"zendesk webhook": "Zendesk Webhook",
	zgrab: "zgrab",
	"zhanzhang.toutiao.com": "Toutiao",
	zipchatbot: "ZipchatBot",
	zoombot: "seozoom-crawler",
	zoominfobot: "ZoomInfo",
	"zoterotranslationserver/wmf": "WMF Zotero Translation Server",
	zumbot: "ZumBot",
};
